CREATE TABLE [Dog_farms] ( 
	[Id] INTEGER PRIMARY KEY, 
	[NAME] VARCHAR(255),  
	[WEBSITE] VARCHAR(255),  
	[FACEBOOK] VARCHAR(255),
	[TWITTER] VARCHAR(255),
	[YOUTUBE] VARCHAR(255),
	[STREET] NVARCHAR(100),
	[CITY] NVARCHAR(100),
	[COUNTRY] NVARCHAR(50),
	[ZIP] INTEGER,
	[X] INTEGER,
	[Y] INTEGER
); 