CREATE TABLE [Dog_farms] ( 
	[Id] INTEGER PRIMARY KEY, 
	[NAME] VARCHAR(255),  
	[WEBSITE] VARCHAR(255),  
	[FACEBOOK] VARCHAR(255),
	[TWITTER] VARCHAR(255),
	[YOUTUBE] VARCHAR(255),
	[ADDRESS] NVARCHAR(255),
	[X] INTEGER,
	[Y] INTEGER,
	[RACES] NVARCHAR(100)
); 